name = "paczka"
author = "Steame"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b525f52c62d7ef58d73cf90f0cc61d51ef7b6397133c180a1c53c2c606d649ed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
