name = "paczka"
author = "Steame"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "647ed0b7501aa16670565558537f05c0ffc5fa9be054308686e64ccf7d8fa99e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
